### ISSUE TITLE
:xml parsing should allow XML declaration

### ISSUE THREAD

**Issue by terjesb** [Raynes/laser#26]
I found another issue with the XML support. It doesn't like the XML declaration (encoding declaration omitted in this example):

``` clojure
(l/document (l/parse "<?xml version=\"1.0\"?><root/>" :xml))
```

IllegalArgumentException No implementation of method: :as-hickory of protocol: #'hickory.core/HickoryRepresentable found for class: org.jsoup.nodes.XmlDeclaration  clojure.core/-cache-protocol-fn (core_deftype.clj:541)

**Comment by Raynes** [comment]
Yeah, I know what's causing this and it shouldn't be particularly hard to fix.

**Comment by Raynes** [comment]
Going to fix this and the other XML issue tomorrow. Sorry it has taken so long. I was in the middle of some breaking changes and wanted to get them all done before I did this excuse excuse more excuses etc etc.

Commenting here so that I have motivation to fix these things tomorrow for real, because now I'll look like an asshat if I don't.

**Comment by Raynes** [comment]
Fixed in the latest commit and will be in the next version.
